"""add models

Revision ID: 5441be63cd5b
Revises: 
Create Date: 2026-04-22 19:02:17.680392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5441be63cd5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity', 'entity_type',
               existing_type=postgresql.ENUM('folder', 'file', 'zipfile', 'zipped_file', 'block', 'layout', 'layer', 'primitive', name='entity_type_enum'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_entity_embedding_ivfflat'), table_name='entity', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_entity_entity_text_gin'), table_name='entity', postgresql_using='gin')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_index(op.f('ix_entity_fts_name_description'), table_name='entity', postgresql_using='gin')
    op.drop_index(op.f('ix_entity_parent_id'), table_name='entity')
    op.drop_index(op.f('ix_entity_project_id'), table_name='entity')
    op.drop_column('entity', 'created_by')
    op.drop_column('entity', 'start_from')
    op.drop_column('entity', 'updated_by')
    op.drop_column('entity', 'updated_at')
    op.drop_index(op.f('ix_entity_to_entity_dst_id'), table_name='entity_to_entity')
    op.drop_index(op.f('ix_entity_to_entity_src_id'), table_name='entity_to_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entity_to_entity_src_id'), 'entity_to_entity', ['src_id'], unique=False)
    op.create_index(op.f('ix_entity_to_entity_dst_id'), 'entity_to_entity', ['dst_id'], unique=False)
    op.add_column('entity', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('updated_by', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('start_from', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('created_by', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_entity_project_id'), 'entity', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_parent_id'), 'entity', ['parent_id'], unique=False)
    op.create_index(op.f('ix_entity_fts_name_description'), 'entity', [sa.literal_column("to_tsvector('russian'::regconfig, (COALESCE(name, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_entity_text_gin'), 'entity', ['entity_text'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_entity_embedding_ivfflat'), 'entity', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('entity', 'entity_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('folder', 'file', 'zipfile', 'zipped_file', 'block', 'layout', 'layer', 'primitive', name='entity_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
