"""add models

Revision ID: d7f2c1d9afee
Revises: 
Create Date: 2026-04-23 16:58:25.764335

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa
import pgvector
import geoalchemy2

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd7f2c1d9afee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_table', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('entity_text', postgresql.TSVECTOR(), nullable=True),
    sa.Column('file_md5', sa.String(length=32), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['entity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_entity_geom', 'entity', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_entity_created_at'), 'entity', ['created_at'], unique=False)
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_geom'), 'entity', ['geom'], unique=False)
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=False)
    op.create_table('entity_to_entity',
    sa.Column('src_id', sa.UUID(), nullable=False),
    sa.Column('dst_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('src_id', 'dst_id', 'link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_to_entity')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_geom'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_index(op.f('ix_entity_created_at'), table_name='entity')
    op.drop_index('idx_entity_geom', table_name='entity', postgresql_using='gist')
    op.drop_table('entity')
    op.drop_table('project')
    # ### end Alembic commands ###
